version: '3.8'
services:
  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  # mongo:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #     MONGO_INITDB_DATABASE: saywub
  #   ports:
  #     - "37017:27017"
  #   volumes:
  #     - data:/data/db
  #     - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  backend:
    image: chaiyapluek/cloud-final-backend:0.1.3
    ports:
      - "8080:8080"
    env_file:
      - .env.local

volumes:
  data: